name: Build Extension

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Setup Cloudsmith CLI
      run: |
          python -m pip install --upgrade pip
          pip install --upgrade cloudsmith-cli

    - name: Install vsce
      run: npm install -g @vscode/vsce 

    - name: Initialize
      id: init
      run: |
        npm install

    - name: Build Extenstion
      id: package
      if: ${{ steps.init.outcome == 'success' }}
      run: |
        vsce package

    - name: Publish CS
      if: ${{ steps.package.outcome == 'success' && github.event_name == 'push' }}
      env:
        CLOUDSMITH_API_KEY: ${{ secrets.PKG_API_KEY }}
      run: ./.github/workflows/cs.upload.sh $(ls ./*.vsix) $(git rev-parse --short HEAD)

    - name: Cleaning Repo
      env: 
        CLOUDSMITH_API_KEY: ${{ secrets.PKG_API_KEY }}
      if: success()
      run: ./.github/workflows/cs.cleanup.sh gap-vscode-enhanced-goto 2